In [52]:
import numpy as np
arr = np.array([1,5,2,9,10], dtype=np.int8)
arr
# array([ 1,  5,  2,  9, 10], dtype=int8)

array([ 1,  5,  2,  9, 10], dtype=int8)

In [53]:
arr[2]=2000
arr

C:\Users\stasf\AppData\Local\Temp\ipykernel_14792\2685055372.py:1: DeprecationWarning: NumPy will stop allowing conversion of out-of-bound Python integers to integer arrays.  The conversion of 2000 to int8 will fail in the future.
For the old behavior, usually:
    np.array(value).astype(dtype)`
will give the desired result (the cast overflows).
  arr[2]=2000


array([  1,   5, -48,   9,  10], dtype=int8)

In [54]:
print(np.float32(99999999))

100000000.0


In [55]:
arr = np.array([1,5,2,9,10], dtype=np.int8)
nd_arr = np.array([
               [12, 45, 78],
               [34, 56, 13],
               [12, 98, 76]
               ], dtype=np.int16)

In [56]:
print(nd_arr.ndim)
print(nd_arr.size)
print(nd_arr.shape)

2
9
(3, 3)


In [57]:
arr, step = np.linspace(-6, 21, 60, endpoint=False, retstep=True)
step

0.45

In [58]:
mystery = np.array([[-13586,  15203,  28445, -27117,  -1781, -17182, -18049],
       [ 25936, -30968,  -1297,  -4593,   6451,  15790,   7181],
       [ 13348,  28049,  28655,  -6012,  21762,  25397,   8225],
       [ 13240,   7994,  32592,  20149,  13754,  11795,   -564],
       [-21725,  -8681,  30305,  22260, -17918,  12578,  29943],
       [-16841, -25392, -17278,  11740,   5916,    -47, -32037]],
      dtype=np.int16)

In [59]:
last=mystery[-1,-1]
print(last)

-32037


In [60]:
line_4=(mystery[3:4,:])[0]
print(line_4)

[13240  7994 32592 20149 13754 11795  -564]


In [61]:
col=mystery[:,-2]
print(col)

[-17182  15790  25397  11795  12578    -47]


In [62]:
part=mystery[1:3,2:5]
part

array([[-1297, -4593,  6451],
       [28655, -6012, 21762]], dtype=int16)

In [63]:
trans=mystery.transpose()
trans

array([[-13586,  25936,  13348,  13240, -21725, -16841],
       [ 15203, -30968,  28049,   7994,  -8681, -25392],
       [ 28445,  -1297,  28655,  32592,  30305, -17278],
       [-27117,  -4593,  -6012,  20149,  22260,  11740],
       [ -1781,   6451,  21762,  13754, -17918,   5916],
       [-17182,  15790,  25397,  11795,  12578,    -47],
       [-18049,   7181,   8225,   -564,  29943, -32037]], dtype=int16)

In [64]:
gg=[[-1297, -4593,  6451]
 [28655, -6012, 21762]
 [32592, 20149, 13754]]

<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
<>:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
C:\Users\stasf\AppData\Local\Temp\ipykernel_14792\3120052952.py:1: SyntaxWarning: list indices must be integers or slices, not tuple; perhaps you missed a comma?
  gg=[[-1297, -4593,  6451]


TypeError: list indices must be integers or slices, not tuple

In [ ]:
part=mystery[1:4,2:5]
part

array([[-1297, -4593,  6451],
       [28655, -6012, 21762],
       [32592, 20149, 13754]], dtype=int16)

In [ ]:
data = np.array([4, 9, -4, 3])
roots = np.sqrt(data)
roots

C:\Users\stasf\AppData\Local\Temp\ipykernel_22172\3612371969.py:2: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [ ]:
roots = np.sqrt(data)
roots

C:\Users\stasf\AppData\Local\Temp\ipykernel_22172\3752651322.py:1: RuntimeWarning: invalid value encountered in sqrt
  roots = np.sqrt(data)


array([2.        , 3.        ,        nan, 1.73205081])

In [ ]:
np.isnan(roots)

array([False, False,  True, False])

In [ ]:
roots[np.isnan(roots)]

array([nan])

In [ ]:
roots[np.isnan(roots)] = 0

In [ ]:
roots

array([2.        , 3.        , 0.        , 1.73205081])

In [ ]:
np.isnan(np.nan)

True

In [ ]:
None==None

True

In [ ]:
mystery = np.array([ 12279., -26024.,  28745.,  np.nan,  31244.,  -2365.,  -6974.,
        -9212., np.nan, -17722.,  16132.,  25933.,  np.nan, -16431.,
        29810.], dtype=np.float32)

nan_index=np.isnan(mystery)
print(nan_index)

[False False False  True False False False False  True False False False
  True False False]


In [ ]:
n_nan = np.size(nan_index.nonzero())
n_nan

3

In [ ]:
mystery_new=mystery.copy()
mystery_new[nan_index]=0
print(mystery_new)

[ 12279. -26024.  28745.      0.  31244.  -2365.  -6974.  -9212.      0.
 -17722.  16132.  25933.      0. -16431.  29810.]


In [ ]:
print(mystery.dtype)
mystery_int=np.int32(mystery_new)
print(mystery_int)

float32
[ 12279 -26024  28745      0  31244  -2365  -6974  -9212      0 -17722
  16132  25933      0 -16431  29810]


In [ ]:
array=np.array(sorted(mystery_int))
print(array)
print(type(array))

[-26024 -17722 -16431  -9212  -6974  -2365      0      0      0  12279
  16132  25933  28745  29810  31244]
<class 'numpy.ndarray'>


In [ ]:
table=array.reshape((5, 3), order='F')
print(table)

[[-26024  -2365  16132]
 [-17722      0  25933]
 [-16431      0  28745]
 [ -9212      0  29810]
 [ -6974  12279  31244]]


In [ ]:
col=table[:,1]
print(col)

[-2365     0     0     0 12279]


In [ ]:
vec1 = np.arange(1, 6)
vec2 = np.linspace(10, 20, 5)
scalar_product = np.sum(vec1 * vec2)
scalar_product

250.0

In [ ]:
print(vec1)
print(vec2)

[1 2 3 4 5]
[10.  12.5 15.  17.5 20. ]


In [ ]:
scalar_product = np.dot(vec1, vec2)
scalar_product

250.0

In [ ]:
a=np.array([23, 34, 27])
b=np.array([-54,1,46])
c=np.array([46,68,54])

fn=np.linalg.norm

len_a=fn(a)
len_b=fn(b)
len_c=fn(c)

ab=a+b
ac=a+c
bc=b+c

len_a_plus_b=fn(ab)
len_a_plus_c=fn(ac)
len_b_plus_c=fn(bc)

print('len a=',len_a)
print('len_b=',len_b)
print('len_c=',len_c)

print('len(a+b) =  ',len_a_plus_b )
print('len (a+c) = ',len_a_plus_c)
print('len (b+c)=',len_b_plus_c)

print('len (a)+len(b) =  ',len_a+len_b )
print('len (a)+len(c) = ',len_a + len_c)
print('len (b) +len(c)=',len_b + len_c)

if len_a_plus_b==len_a+len_b:
    print('a and b is collinear')
    
if len_a_plus_c==len_a+len_c:
    print('a and c is collinear')
    
if len_b_plus_c==len_b+len_c:
    print('b and c is collinear')


len a= 49.13247398615299
len_b= 70.94363960215179
len_c= 98.26494797230598
len(a+b) =   86.68909966079934
len (a+c) =  147.39742195845895
len (b+c)= 121.75795661885921
len (a)+len(b) =   120.07611358830478
len (a)+len(c) =  147.39742195845895
len (b) +len(c)= 169.20858757445777
a and c is collinear


In [ ]:
#from hidden import *

#import numpy as np

print(a)
print(b)
print(c)
ab=a+b
ac=a+c
bc=b+c

len_a=np.linalg.norm(a)
len_b=np.linalg.norm(b)
len_c=np.linalg.norm(c)

len_ab=np.linalg.norm(ab)
len_ac=np.linalg.norm(ac)
len_bc=np.linalg.norm(bc)

razn_ab=len_ab-len_a-len_b
razn_ac=len_ac-len_a-len_c
razn_bc=len_bc-len_b-len_c

print('a b',razn_ab)
print('a c',razn_ac)
print('b c',razn_bc)

[23 34 27]
[-54   1  46]
[46 68 54]
a b -33.387013927505436
a c -1.4210854715202004e-14
b c -47.450630955598555


In [ ]:
fn=np.linalg.norm

print('a - b',fn(a-b))
print('a - c',fn(a-c))
print('b - c',fn(b-c))

a - b 85.901105930017
a - c 49.13247398615299
b - c 120.6358155772986


In [ ]:
import numpy as np
fn1=np.dot
print('a b',np.dot(a,b))
print('a c',np.dot(a,c))
print('b c',np.dot(b,c))

a b 34
a c 4828
b c 68


In [ ]:
sh=(3,4)
print(*sh)

3 4


In [ ]:
np.random.seed(100)
print(np.random.randint(10, size=3))
# [8 8 3]
print(np.random.randint(10, size=3))
# [7 7 0]
print(np.random.randint(10, size=3))
# [4 2 5]


[8 8 3]
[7 7 0]
[4 2 5]


In [ ]:
import numpy as np

p=print

np.random.seed(2021)

simple=np.random.rand()

randoms=np.random.uniform(-150,2022,size=120)

table=np.random.randint(1,101,size=(3,2))

even=np.arange(2,18,2)

mix=np.random.permutation(even)

select=np.random.choice(even, size=3, replace=False)

triplet=np.random.permutation(select)

print(simple)
print('table ',table)


p(even)
p(mix)
p('sel ',select)
p('trp ' ,triplet)
p('sel ',select)


0.6059782788074047
table  [[46 93]
 [35 41]
 [17 45]]
[ 2  4  6  8 10 12 14 16]
[ 6 10  2  8 14 16  4 12]
sel  [14  2  4]
trp  [ 2  4 14]
sel  [14  2  4]


In [ ]:
def get_chess(a=1):
    chs=np.zeros((a,a))
    print('old ',chs)
    chs[range(0,a,2),1::2]=1
    chs[range(1,a,2),::2]=1
    #print('---',chs[0:a,0:a][0::2])

    print('new ',chs)
    
    
print(get_chess(a = 1))

#print(*range(1,3,2))

old  [[0.]]
new  [[0.]]
None


In [ ]:
arr=np.array(range(5))
print(arr)
seed_cur=np.random.random()
np.random.seed=seed_cur
np.random.shuffle(arr,3)
print(arr)
print(seed_cur)

[0 1 2 3 4]


TypeError: RandomState.shuffle() takes exactly one argument (2 given)

In [ ]:
arr=np.array(range(5))
print(arr)
key_sort=np.random.random()
B = sorted(arr, key=lambda x: key_sort)
print(B)

[0 1 2 3 4]
[0, 1, 2, 3, 4]


In [ ]:
def shuffle_seed(array): 
    seed = np.random.randint(2**31)
    np.random.seed=seed
    result = np.random.permutation(array)
    return result, seed 

arr=np.array(range(5))
print(shuffle_seed(arr))


(array([0, 1, 4, 3, 2]), 1521212522)


In [65]:
def get_loto(num):
    res_arr=[]
    for i in range(num):
        

SyntaxError: incomplete input (3133169480.py, line 4)

In [91]:
def get_loto(num):     
    l_num=np.array(range(101))
    print(l_num)
    arr=np.zeros((num,5,5),dtype=int)
    for i in range(num):
        l_uniq=np.random.permutation(l_num)
        arr[i]=l_uniq[0:25].reshape((5,5))
        print('arr ',arr[i])
    return arr   
   
    
print(get_loto(3))

[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100]
arr  [[ 24  36  79  70  90]
 [ 25   3   8  67  75]
 [ 19  74  99  60  92]
 [  9  49 100  44  68]
 [ 91  48  35  73  81]]
arr  [[ 5 27 36 41 25]
 [18 14 70 64 91]
 [56 86 97 32 38]
 [13 33 20 35 94]
 [16 73 82 55 26]]
arr  [[ 61  60  83   7  86]
 [ 24  29   6  56  74]
 [ 34  65   9  19  89]
 [ 21  76  96  52  48]
 [ 67  85  40 100  51]]
[[[ 24  36  79  70  90]
  [ 25   3   8  67  75]
  [ 19  74  99  60  92]
  [  9  49 100  44  68]
  [ 91  48  35  73  81]]

 [[  5  27  36  41  25]
  [ 18  14  70  64  91]
  [ 56  86  97  32  38]
  [ 13  33  20  35  94]
  [ 16  73  82  55  26]]

 [[ 61 

In [92]:
def get_unique_loto(num):     
   
    arr=np.zeros((num,5,5),dtype=int)
    return arr   
   
    
print(get_unique_loto(3))

[[[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]

 [[0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]
  [0 0 0 0 0]]]


In [97]:
simplelist = [19, 242, 14, 152, 142, 1000]
arr=np.array(simplelist)
print(np.mean(arr))

261.5
